// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wpexport} from '../models';
import {history} from '../models';
import {config} from '../models';
import {scanner} from '../models';
import {main} from '../models';
import {optimizer} from '../models';
import {profiles} from '../models';
import {cloud} from '../models';
import {w3c} from '../models';

export function CancelScan():Promise<void>;

export function CompareExportPackages(arg1:string,arg2:string):Promise<wpexport.ExportDiffReport>;

export function CompareHistoryRuns(arg1:string,arg2:string):Promise<history.RunsDiffResult>;

export function ComputeSiteAnalytics(arg1:string,arg2:config.ScanConfig,arg3:Array<scanner.PageResult>):Promise<main.AnalyticsResult>;

export function ConvertImageToWebP(arg1:string,arg2:config.ScanConfig):Promise<optimizer.ConversionResult>;

export function DeleteSiteProfile(arg1:string):Promise<void>;

export function DisconnectGDrive():Promise<void>;

export function DownloadOptimizedWebPZIP(arg1:Array<string>,arg2:config.ScanConfig):Promise<string>;

export function DownloadSingleWebPImage(arg1:string,arg2:config.ScanConfig):Promise<string>;

export function DownloadSingleWebPTuned(arg1:string,arg2:optimizer.ImageTuneOptions,arg3:config.ScanConfig):Promise<string>;

export function ExportFontsCSV(arg1:string):Promise<string>;

export function ExportFontsJSON(arg1:string):Promise<string>;

export function ExportFormsCSV(arg1:string):Promise<string>;

export function ExportFormsJSON(arg1:string):Promise<string>;

export function ExportIframesCSV(arg1:string):Promise<string>;

export function ExportIframesJSON(arg1:string):Promise<string>;

export function ExportImageComparisonHTML(arg1:string,arg2:config.ScanConfig,arg3:Array<scanner.PageResult>):Promise<string>;

export function ExportWordPressWebPApplyPHP(arg1:string,arg2:config.ScanConfig,arg3:Array<scanner.PageResult>,arg4:string):Promise<wpexport.ExportResult>;

export function ExportWordPressWebPApplyPHPWithOverrides(arg1:string,arg2:config.ScanConfig,arg3:Array<scanner.PageResult>,arg4:string,arg5:Record<string, wpexport.ImageOverride>):Promise<wpexport.ExportResult>;

export function GetAllHistoryRuns(arg1:string):Promise<Array<history.ScanRunSummary>>;

export function GetExportHistory(arg1:string):Promise<Array<wpexport.ExportRecord>>;

export function GetGDriveCredentials():Promise<Record<string, string>>;

export function GetGDriveStatus():Promise<Record<string, any>>;

export function ListSiteProfiles():Promise<Array<profiles.SiteProfile>>;

export function OpenURL(arg1:string):Promise<void>;

export function ParseSitemap(arg1:string,arg2:config.ScanConfig):Promise<Array<string>>;

export function PlayNotificationSound(arg1:string):Promise<void>;

export function PreviewImageComparisonHTML(arg1:string,arg2:config.ScanConfig,arg3:Array<scanner.PageResult>):Promise<string>;

export function RescanSingleURL(arg1:config.ScanConfig,arg2:string,arg3:number):Promise<scanner.PageResult>;

export function ResolveDomain(arg1:string):Promise<scanner.DomainResolution>;

export function SaveGDriveCredentials(arg1:string,arg2:string):Promise<void>;

export function SaveSiteProfile(arg1:profiles.SiteProfile):Promise<profiles.SiteProfile>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SendSystemNotification(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartGDriveAuth(arg1:string,arg2:string):Promise<string>;

export function StartScan(arg1:config.ScanConfig,arg2:Array<string>):Promise<void>;

export function TuneImagePreview(arg1:string,arg2:optimizer.ImageTuneOptions,arg3:config.ScanConfig):Promise<optimizer.ConversionResult>;

export function UploadFileToGDrive(arg1:string,arg2:string):Promise<cloud.DriveUploadResult>;

export function ValidateW3C(arg1:string):Promise<w3c.W3CReport>;
