// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function ComputeSiteAnalytics(arg1, arg2, arg3) {
  return window['go']['main']['App']['ComputeSiteAnalytics'](arg1, arg2, arg3);
}

export function ConvertImageToWebP(arg1, arg2) {
  return window['go']['main']['App']['ConvertImageToWebP'](arg1, arg2);
}

export function DeleteSiteProfile(arg1) {
  return window['go']['main']['App']['DeleteSiteProfile'](arg1);
}

export function DownloadOptimizedWebPZIP(arg1, arg2) {
  return window['go']['main']['App']['DownloadOptimizedWebPZIP'](arg1, arg2);
}

export function DownloadSingleWebPImage(arg1, arg2) {
  return window['go']['main']['App']['DownloadSingleWebPImage'](arg1, arg2);
}

export function ExportFontsCSV(arg1) {
  return window['go']['main']['App']['ExportFontsCSV'](arg1);
}

export function ExportFontsJSON(arg1) {
  return window['go']['main']['App']['ExportFontsJSON'](arg1);
}

export function ExportImageComparisonHTML(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportImageComparisonHTML'](arg1, arg2, arg3);
}

export function ExportWordPressWebPApplyPHP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportWordPressWebPApplyPHP'](arg1, arg2, arg3, arg4);
}

export function ListSiteProfiles() {
  return window['go']['main']['App']['ListSiteProfiles']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ParseSitemap(arg1, arg2) {
  return window['go']['main']['App']['ParseSitemap'](arg1, arg2);
}

export function PlayNotificationSound(arg1) {
  return window['go']['main']['App']['PlayNotificationSound'](arg1);
}

export function PreviewImageComparisonHTML(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewImageComparisonHTML'](arg1, arg2, arg3);
}

export function RescanSingleURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['RescanSingleURL'](arg1, arg2, arg3);
}

export function SaveSiteProfile(arg1) {
  return window['go']['main']['App']['SaveSiteProfile'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}

export function ValidateW3C(arg1) {
  return window['go']['main']['App']['ValidateW3C'](arg1);
}
