// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {scanner} from '../models';
import {main} from '../models';
import {w3c} from '../models';

export function CancelScan():Promise<void>;

export function ComputeSiteAnalytics(arg1:string,arg2:config.ScanConfig,arg3:Array<scanner.PageResult>):Promise<main.AnalyticsResult>;

export function ExportImageComparisonHTML(arg1:string,arg2:config.ScanConfig,arg3:Array<scanner.PageResult>):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function ParseSitemap(arg1:string,arg2:config.ScanConfig):Promise<Array<string>>;

export function PreviewImageComparisonHTML(arg1:string,arg2:config.ScanConfig,arg3:Array<scanner.PageResult>):Promise<string>;

export function RescanSingleURL(arg1:config.ScanConfig,arg2:string,arg3:number):Promise<scanner.PageResult>;

export function StartScan(arg1:config.ScanConfig,arg2:Array<string>):Promise<void>;

export function ValidateW3C(arg1:string):Promise<w3c.W3CReport>;
