// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function ComputeSiteAnalytics(arg1, arg2, arg3) {
  return window['go']['main']['App']['ComputeSiteAnalytics'](arg1, arg2, arg3);
}

export function ExportImageComparisonHTML(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportImageComparisonHTML'](arg1, arg2, arg3);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ParseSitemap(arg1, arg2) {
  return window['go']['main']['App']['ParseSitemap'](arg1, arg2);
}

export function PreviewImageComparisonHTML(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewImageComparisonHTML'](arg1, arg2, arg3);
}

export function RescanSingleURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['RescanSingleURL'](arg1, arg2, arg3);
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}

export function ValidateW3C(arg1) {
  return window['go']['main']['App']['ValidateW3C'](arg1);
}
